import type { Pool } from "pg";

/** Idempotent Brain-owned tables (Better Auth tables come from getMigrations). */
export async function ensureBrainSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS brain_workspace (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      kind TEXT NOT NULL CHECK (kind IN ('personal', 'team')),
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS brain_workspace_member (
      workspace_id TEXT NOT NULL REFERENCES brain_workspace(id) ON DELETE CASCADE,
      user_id TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
      created_at TEXT NOT NULL,
      PRIMARY KEY (workspace_id, user_id)
    );

    CREATE INDEX IF NOT EXISTS brain_workspace_member_user_idx
      ON brain_workspace_member (user_id);

    CREATE TABLE IF NOT EXISTS brain_instance_policy (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      signup_mode TEXT NOT NULL,
      auto_personal_workspace BOOLEAN NOT NULL,
      allow_create_workspace BOOLEAN NOT NULL,
      allow_forgot_password BOOLEAN NOT NULL DEFAULT TRUE
    );

    CREATE TABLE IF NOT EXISTS brain_instance_admin (
      user_id TEXT PRIMARY KEY NOT NULL
    );

    CREATE TABLE IF NOT EXISTS brain_user_active_workspace (
      user_id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT NOT NULL REFERENCES brain_workspace(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS brain_workspace_invite (
      id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT NOT NULL REFERENCES brain_workspace(id) ON DELETE CASCADE,
      token TEXT NOT NULL UNIQUE,
      email TEXT,
      role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
      created_by_user_id TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      revoked_at TEXT,
      created_at TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS brain_workspace_invite_workspace_idx
      ON brain_workspace_invite (workspace_id);

    CREATE TABLE IF NOT EXISTS brain_bootstrap_claim (
      id INTEGER PRIMARY KEY CHECK (id = 1)
    );

    CREATE TABLE IF NOT EXISTS chat (
      id TEXT PRIMARY KEY NOT NULL,
      user_id TEXT NOT NULL,
      workspace_id TEXT NOT NULL,
      visibility TEXT NOT NULL DEFAULT 'personal',
      title TEXT NOT NULL,
      eve_session TEXT,
      revision INTEGER NOT NULL DEFAULT 0,
      turn_lock_user_id TEXT,
      turn_lock_until TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS chat_event (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      chat_id TEXT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
      event_index INTEGER NOT NULL,
      event TEXT NOT NULL,
      UNIQUE (chat_id, event_index)
    );

    CREATE INDEX IF NOT EXISTS chat_updated_at_idx ON chat (updated_at DESC);
    CREATE INDEX IF NOT EXISTS chat_event_chat_id_idx ON chat_event (chat_id, event_index);
    CREATE INDEX IF NOT EXISTS chat_user_workspace_updated_at_idx
      ON chat (user_id, workspace_id, updated_at DESC);
    CREATE INDEX IF NOT EXISTS chat_workspace_visibility_updated_at_idx
      ON chat (workspace_id, visibility, updated_at DESC);

    CREATE TABLE IF NOT EXISTS playbook (
      id TEXT PRIMARY KEY NOT NULL,
      user_id TEXT NOT NULL,
      workspace_id TEXT,
      label TEXT NOT NULL,
      prompt TEXT NOT NULL,
      updated_at BIGINT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS playbook_user_updated_idx
      ON playbook (user_id, updated_at DESC);
    CREATE INDEX IF NOT EXISTS playbook_workspace_updated_idx
      ON playbook (workspace_id, updated_at DESC);

    CREATE TABLE IF NOT EXISTS playbook_schedule (
      id TEXT PRIMARY KEY NOT NULL,
      user_id TEXT NOT NULL,
      workspace_id TEXT,
      run_as_user_id TEXT,
      label TEXT NOT NULL,
      prompt TEXT NOT NULL,
      source_playbook_id TEXT,
      enabled BOOLEAN NOT NULL,
      hour INTEGER NOT NULL,
      minute INTEGER NOT NULL,
      timezone TEXT NOT NULL,
      weekdays_only BOOLEAN NOT NULL,
      slack_delivery_enabled BOOLEAN NOT NULL,
      slack_channel TEXT,
      last_slack_error TEXT,
      last_run_date_key TEXT,
      last_chat_id TEXT,
      last_run_at TEXT,
      running_since TEXT
    );

    CREATE INDEX IF NOT EXISTS playbook_schedule_user_idx ON playbook_schedule (user_id);
    CREATE INDEX IF NOT EXISTS playbook_schedule_workspace_idx ON playbook_schedule (workspace_id);

    CREATE TABLE IF NOT EXISTS morning_brief_schedule (
      user_id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT,
      run_as_user_id TEXT,
      enabled BOOLEAN NOT NULL,
      hour INTEGER NOT NULL,
      minute INTEGER NOT NULL,
      timezone TEXT NOT NULL,
      weekdays_only BOOLEAN NOT NULL,
      slack_delivery_enabled BOOLEAN NOT NULL,
      slack_channel TEXT,
      last_slack_error TEXT,
      last_run_date_key TEXT,
      last_chat_id TEXT,
      last_run_at TEXT,
      running_since TEXT
    );

    CREATE INDEX IF NOT EXISTS morning_brief_schedule_workspace_idx
      ON morning_brief_schedule (workspace_id);

    INSERT INTO brain_instance_policy (
      id, signup_mode, auto_personal_workspace, allow_create_workspace, allow_forgot_password
    ) VALUES (1, 'invite-only', TRUE, TRUE, TRUE)
    ON CONFLICT (id) DO NOTHING;
  `);
}
