import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { SNOWFLAKE_MCP_URL_ENV, SNOWFLAKE_PLACEHOLDER_MCP_URL } from "../connections/snowflake-env";
import { resolveProviderMcpUrlSync } from "./connection-credentials";

/**
 * Eve bakes `defineMcpClientConnection({ url })` into
 * `compiled-agent-manifest.json` at compile time and uses that manifest URL
 * at runtime (not a live re-read of the module export).
 *
 * Touching `snowflake.ts` is not enough: content-identical rebuilds can keep
 * the placeholder URL. Writing this generated module changes source content so
 * eve recompiles with the account MCP URL as a string literal.
 */
export const SNOWFLAKE_MCP_URL_GENERATED_RELATIVE = path.join(
  "agent",
  "connections",
  "snowflake-mcp-url.generated.ts",
);

export function renderSnowflakeCompiledMcpUrlModule(mcpUrl: string): string {
  const trimmed = mcpUrl.trim() || SNOWFLAKE_PLACEHOLDER_MCP_URL;
  return `/**
 * Generated by Connections → Snowflake → Set up.
 * Eve compiles this string into the connection manifest — do not hand-edit.
 */
export const SNOWFLAKE_COMPILED_MCP_URL = ${JSON.stringify(trimmed)} as const;
`;
}

/**
 * Write (or reset) the compiled MCP URL module so eve rebuilds with the new URL.
 * Pass `mcpUrl` explicitly from Set up; omit to read stored/env credentials;
 * pass `null` to reset to the placeholder.
 */
export async function reloadSnowflakeConnectionModule(
  cwd: string = process.cwd(),
  mcpUrl?: string | null,
): Promise<void> {
  const previousCwd = process.cwd();
  if (cwd !== previousCwd) {
    process.chdir(cwd);
  }
  try {
    const resolved =
      mcpUrl === undefined
        ? resolveProviderMcpUrlSync({
            name: "snowflake",
            mcpUrlEnv: SNOWFLAKE_MCP_URL_ENV,
          })
        : mcpUrl;
    const nextUrl = resolved?.trim() || SNOWFLAKE_PLACEHOLDER_MCP_URL;
    const destination = path.join(cwd, SNOWFLAKE_MCP_URL_GENERATED_RELATIVE);
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, renderSnowflakeCompiledMcpUrlModule(nextUrl), "utf8");
  } finally {
    if (cwd !== previousCwd) {
      process.chdir(previousCwd);
    }
  }
}
