/**
 * Generated by Connections → Snowflake → Set up.
 * Eve compiles this string into the connection manifest — do not hand-edit.
 */
export const SNOWFLAKE_COMPILED_MCP_URL =
  "https://org-account.snowflakecomputing.com/api/v2/databases/EXAMPLE/schemas/EXAMPLE/mcp-servers/EXAMPLE" as const;
